export const teamMembers = [
    {
        id: 1,
        name: 'Bastiyan Rodrigo',
        title: 'Founder & Director',
        image: '/members/bastiyan.jpg',
        description: `Prior to founding BLYMO, Bastiyan Rodrigo worked at the University of Oxford, where he collaborated with world-class academic research groups, bridging the gap between rigorous scientific evidence and scalable software architectures. His journey in the tech industry spans over 12 years. 
        He completed his schooling at St Joseph’s College, Colombo, before migrating to the UK in 2011 to pursue higher education. Throughout his career in the UK, Bastiyan has gained extensive experience across various industries, witnessing firsthand how technological innovation drives progress.
        Bastiyan has contributed to a range of organizations, from SaaS startups to world-renowned academic institutes. His passion for technology and innovation led to the creation of BLYMO, a venture inspired by his vision of supporting organizations and individuals with aspirations for the future.
        An avid learner, Bastiyan dedicates significant time to mastering new technologies, applying his insights to enhance client solutions continuously. Outside of his professional life, he enjoys spending time with his family and engaging in DIY projects.`
    },
    {
        id: 2,
        name: 'Malki Rodrigo',
        title: 'Product Researcher & Impact Lead',
        image: '/members/malki.jpg',
        description: `Malki is a dedicated product researcher with a passion for uncovering insights that drive successful product development and market strategies. With a strong background in data analysis, research, and data interpretation, she is committed to understanding consumer needs and translating them into actionable recommendations. She holds a bachelor’s degree in Town and Country Planning and a master’s degree in Environmental Management.
        Malki has extensive experience in urban research, with a focus on sustainability and spatial data analytics. Her attention to detail and knack for conducting thorough analyses have been instrumental in BLYMO's impact-measurement methodologies, ensuring that our research is both comprehensive and aligned with academic standards.
        In her role as Impact Lead, she coordinates the design of evaluation protocols, user feedback loops, and metrics monitoring to align digital solutions with positive behavioural change.`
    },
    {
        id: 3,
        name: 'Ashen Karunarathne',
        title: 'Fullstack Engineer / CTO Lead',
        image: '/members/ashen.jpg',
        description: `Ashen is a dedicated full stack software engineer leading BLYMO's core platform architecture and engineering execution. With a robust foundation of about 5 years in the industry, he specializes in Laravel (PHP), Node.js, Vue.js, MySQL, NoSQL, and next-generation frameworks. He holds a degree from the University of Kelaniya and is currently pursuing his MSc in Computer Science.
        His expertise is critical in structuring secure database logic, cloud hosting environments, and the secure AI processing/retrieval layers (RAG) required by modern behavioral engines. Ashen ensures all engineering outputs meet strict security, scalability, and GDPR-compliance guidelines.`
    },
    {
        id: 4,
        name: 'Imanthi Jayakodi',
        title: 'UX Engineer & Designer',
        image: '/members/imanthi.jpg',
        description: `Imanthi is a seasoned UI/UX Engineer specialized in turning complex user journeys into delightful, intuitive digital products. She is a computer science undergrad at IIT affiliated with the University of Westminster, specializing in multimedia pathways. 
        Imanthi is highly proficient in HTML, SCSS, Figma, and user-centric wireframing. Her approach to creating interfaces is focused on delivering engaging, accessible user experiences with a strong emphasis on micro-animations and inclusive design. She leads the design system architecture for BLYMO's venture incubator, ensuring interfaces feel welcoming, modern, and human.`
    },
    {
        id: 5,
        name: 'Dr. Sarah Jenkins',
        title: 'Behavioural Advisor',
        image: '/members/luchie.jpg',
        description: `Dr. Sarah Jenkins is a behavioural science consultant advising BLYMO on nudge mechanics, habit loop design, and retention strategies. Her work focuses on translating psychological theory into micro-actions that fit seamlessly into daily family routines, maximizing positive outcomes without adding cognitive load.`
    },
    {
        id: 6,
        name: 'Professor Charles Vance',
        title: 'Early Years Advisor',
        image: '/members/hasitha.jpg',
        description: `Professor Charles Vance is a child development specialist advising on developmental milestones, age-appropriate interactions, and home learning environments. He ensures that all story prompts and activities generated by the platform are scientifically aligned with early-years developmental goals.`
    },
    {
        id: 7,
        name: 'Rachel Adams',
        title: 'Pilot Coordinator (Part-time)',
        image: '/members/luchie-bg-white.jpg',
        description: `Rachel manages onboarding, pilot logistics, and stakeholder relations with midwives, health visitors, and family support groups. She coordinates active testing cohorts, logs user feedback, and ensures our pilot programs run smoothly and safely.`
    }
];